/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppProductsIndexRouteImport } from './pages/_app/products/index'
import { Route as AppOurStoresIndexRouteImport } from './pages/_app/our-stores/index'
import { Route as AppAboutIndexRouteImport } from './pages/_app/about/index'
import { Route as AppProductsProductIdRouteImport } from './pages/_app/products/$productId'
import { Route as AppAuthSignUpRouteImport } from './pages/_app/_auth/sign-up'
import { Route as AppAuthSignInRouteImport } from './pages/_app/_auth/sign-in'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOurStoresIndexRoute = AppOurStoresIndexRouteImport.update({
  id: '/our-stores/',
  path: '/our-stores/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAboutIndexRoute = AppAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAuthSignUpRoute = AppAuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAuthSignInRoute = AppAuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AppAuthSignInRoute
  '/sign-up': typeof AppAuthSignUpRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/about/': typeof AppAboutIndexRoute
  '/our-stores/': typeof AppOurStoresIndexRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AppAuthSignInRoute
  '/sign-up': typeof AppAuthSignUpRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/about': typeof AppAboutIndexRoute
  '/our-stores': typeof AppOurStoresIndexRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/_auth/sign-in': typeof AppAuthSignInRoute
  '/_app/_auth/sign-up': typeof AppAuthSignUpRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/about/': typeof AppAboutIndexRoute
  '/_app/our-stores/': typeof AppOurStoresIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/products/$productId'
    | '/about/'
    | '/our-stores/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/products/$productId'
    | '/about'
    | '/our-stores'
    | '/products'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/_auth/sign-in'
    | '/_app/_auth/sign-up'
    | '/_app/products/$productId'
    | '/_app/about/'
    | '/_app/our-stores/'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/our-stores/': {
      id: '/_app/our-stores/'
      path: '/our-stores'
      fullPath: '/our-stores/'
      preLoaderRoute: typeof AppOurStoresIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/about/': {
      id: '/_app/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AppAboutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_auth/sign-up': {
      id: '/_app/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AppAuthSignUpRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_auth/sign-in': {
      id: '/_app/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AppAuthSignInRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAuthSignInRoute: typeof AppAuthSignInRoute
  AppAuthSignUpRoute: typeof AppAuthSignUpRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppAboutIndexRoute: typeof AppAboutIndexRoute
  AppOurStoresIndexRoute: typeof AppOurStoresIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAuthSignInRoute: AppAuthSignInRoute,
  AppAuthSignUpRoute: AppAuthSignUpRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppAboutIndexRoute: AppAboutIndexRoute,
  AppOurStoresIndexRoute: AppOurStoresIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
